from dataclasses import dataclass, field


@dataclass
class CandidateSpecification:
    role: str
    seniority: str
    country: str
    city: str
    university: str
    gender: str
    skills: list[str] = field(default_factory=list)
    years_of_experience: int = 5


class CandidateSpecificationCatalog:
    """Holds the fixed catalog of synthetic candidate specifications used for generation."""

    _SPECS: list[CandidateSpecification] = [
        CandidateSpecification(
            "Backend Engineering",
            "Senior",
            "Spain",
            "Barcelona",
            "Universitat Politècnica de Catalunya (UPC)",
            "woman",
            ["Python", "PostgreSQL", "Docker"],
            7,
        ),
        CandidateSpecification(
            "AI / ML Engineering",
            "Mid",
            "Spain",
            "Barcelona",
            "Universitat Politècnica de Catalunya (UPC)",
            "man",
            ["Python", "LangChain", "LangGraph", "GCP"],
            4,
        ),
        CandidateSpecification(
            "Data Science",
            "Senior",
            "Spain",
            "Madrid",
            "Universidad Politécnica de Madrid",
            "woman",
            ["Python", "Machine Learning", "SQL"],
            8,
        ),
        CandidateSpecification(
            "Full-stack Engineering",
            "Mid",
            "Spain",
            "Valencia",
            "Universitat Politècnica de Catalunya (UPC)",
            "man",
            ["React", "Node.js", "TypeScript"],
            5,
        ),
        CandidateSpecification(
            "Frontend Engineering",
            "Junior",
            "Portugal",
            "Lisbon",
            "Instituto Superior Técnico",
            "woman",
            ["React", "TypeScript", "Vite"],
            2,
        ),
        CandidateSpecification(
            "Backend Engineering",
            "Lead",
            "Germany",
            "Berlin",
            "Technical University of Munich",
            "man",
            ["Java", "Kubernetes", "AWS"],
            11,
        ),
        CandidateSpecification(
            "Data Engineering",
            "Mid",
            "Poland",
            "Warsaw",
            "Warsaw University of Technology",
            "woman",
            ["Python", "Airflow", "SQL", "GCP"],
            5,
        ),
        CandidateSpecification(
            "DevOps / SRE",
            "Senior",
            "Netherlands",
            "Amsterdam",
            "Delft University of Technology",
            "man",
            ["Kubernetes", "Terraform", "AWS"],
            8,
        ),
        CandidateSpecification(
            "Product Management",
            "Senior",
            "France",
            "Paris",
            "HEC Paris",
            "woman",
            ["Product Strategy", "SQL", "A/B Testing"],
            9,
        ),
        CandidateSpecification(
            "Product Management",
            "Mid",
            "Ireland",
            "Dublin",
            "Trinity College Dublin",
            "man",
            ["Roadmapping", "User Research", "Jira"],
            4,
        ),
        CandidateSpecification(
            "UX / Product Design",
            "Mid",
            "Italy",
            "Milan",
            "Politecnico di Milano",
            "woman",
            ["Figma", "Design Systems", "User Research"],
            5,
        ),
        CandidateSpecification(
            "UX / Product Design",
            "Junior",
            "Brazil",
            "São Paulo",
            "Universidade de São Paulo (USP)",
            "man",
            ["Figma", "Prototyping"],
            2,
        ),
        CandidateSpecification(
            "AI / ML Engineering",
            "Senior",
            "United States",
            "Austin",
            "University of Texas at Austin",
            "man",
            ["Python", "PyTorch", "LangChain"],
            8,
        ),
        CandidateSpecification(
            "Data Science",
            "Mid",
            "India",
            "Bengaluru",
            "Indian Institute of Technology (IIT) Bombay",
            "woman",
            ["Python", "Machine Learning", "Pandas"],
            4,
        ),
        CandidateSpecification(
            "Backend Engineering",
            "Mid",
            "Nigeria",
            "Lagos",
            "University of Lagos",
            "man",
            ["Node.js", "Express", "PostgreSQL"],
            5,
        ),
        CandidateSpecification(
            "QA / Test Automation",
            "Mid",
            "Kenya",
            "Nairobi",
            "University of Nairobi",
            "woman",
            ["Selenium", "Python", "CI/CD"],
            5,
        ),
        CandidateSpecification(
            "Full-stack Engineering",
            "Senior",
            "Mexico",
            "Mexico City",
            "Tecnológico de Monterrey",
            "man",
            ["React", "Node.js", "AWS"],
            7,
        ),
        CandidateSpecification(
            "Data Engineering",
            "Senior",
            "Argentina",
            "Buenos Aires",
            "Universidad de Buenos Aires",
            "woman",
            ["Python", "SQL", "Airflow"],
            8,
        ),
        CandidateSpecification(
            "Marketing (Growth)",
            "Mid",
            "United Kingdom",
            "London",
            "University of Manchester",
            "woman",
            ["SEO", "Google Analytics", "A/B Testing"],
            5,
        ),
        CandidateSpecification(
            "Marketing (Content)",
            "Junior",
            "Canada",
            "Toronto",
            "University of Toronto",
            "man",
            ["Content Strategy", "SEO"],
            2,
        ),
        CandidateSpecification(
            "Sales / Business Development",
            "Senior",
            "United States",
            "New York",
            "New York University",
            "man",
            ["B2B SaaS Sales", "Salesforce", "Negotiation"],
            9,
        ),
        CandidateSpecification(
            "Customer Success",
            "Mid",
            "Philippines",
            "Manila",
            "University of the Philippines",
            "woman",
            ["Onboarding", "CRM", "Zendesk"],
            4,
        ),
        CandidateSpecification(
            "Finance / Analyst",
            "Mid",
            "Egypt",
            "Cairo",
            "American University in Cairo",
            "man",
            ["Financial Modeling", "Excel", "SQL"],
            5,
        ),
        CandidateSpecification(
            "People / HR Ops",
            "Senior",
            "South Africa",
            "Cape Town",
            "University of Cape Town",
            "woman",
            ["Recruiting", "HRIS", "People Analytics"],
            8,
        ),
        CandidateSpecification(
            "Project Management",
            "Senior",
            "Vietnam",
            "Ho Chi Minh City",
            "Vietnam National University",
            "man",
            ["Agile", "Scrum", "Stakeholder Management"],
            9,
        ),
        CandidateSpecification(
            "Backend Engineering",
            "Junior",
            "Spain",
            "Barcelona",
            "Universitat de Barcelona (UB)",
            "woman",
            ["Python", "Flask", "PostgreSQL"],
            2,
        ),
        CandidateSpecification(
            "AI / ML Engineering",
            "Lead",
            "Germany",
            "Munich",
            "Ludwig Maximilian University of Munich",
            "woman",
            ["Python", "LangGraph", "MLOps", "GCP"],
            10,
        ),
        CandidateSpecification(
            "Data Science",
            "Junior",
            "Colombia",
            "Bogotá",
            "Universidad de los Andes",
            "man",
            ["Python", "SQL", "Statistics"],
            1,
        ),
    ]

    @classmethod
    def all(cls) -> list[CandidateSpecification]:
        """Return a copy of all candidate specs."""
        return list(cls._SPECS)


CANDIDATE_SPECS: list[CandidateSpecification] = CandidateSpecificationCatalog.all()